package cmd

import (
	"fmt"
	"sort"

	"github.com/spf13/cobra"
)

func newCommandsCommand() *cobra.Command {
	commands := map[string]string{
		"commands":    "Lists commands available in muxi",
		"completions": "Used for shell completion",
		"copy":        "Copy an existing project to a new project",
		"debug":       "Output the shell commands generated by muxi",
		"delete":      "Deletes given project",
		"doctor":      "Look for problems in your configuration",
		"implode":     "Deletes all muxi projects",
		"local":       "Start a tmux session using ./.tmuxinator.yml",
		"list":        "Lists all muxi projects",
		"new":         "Create a new project file and open it in your editor",
		"start":       "Start a tmux session from a project or config path",
		"stop":        "Stop a tmux session using a project's config",
		"stop_all":    "Stop all tmux sessions using muxi projects",
		"version":     "Display installed muxi version",
	}
	return &cobra.Command{
		Use:   "commands",
		Short: "List muxi commands",
		Run: func(cmd *cobra.Command, args []string) {
			keys := make([]string, 0, len(commands))
			for key := range commands {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			for _, key := range keys {
				fmt.Fprintln(cmd.OutOrStdout(), key)
			}
		},
	}
}
